### ISSUE TITLE
mongo

### ISSUE THREAD

**Issue by colinricardo** [thislekan/codecubed-todo#4]
can't connect to mongo, getting error: 

```
(node:70708) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:16) {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]
```

**Comment by thislekan** [comment]
hello @colinricardo 

Can I see your connection string? I didn't use my local DB to connect. That's why I pushed my code with the connection string to my online `mlab DB`. However, to connect to your local DB, your connection string should look like the image below.

<img width="526" alt="Screenshot 2019-12-16 at 9 18 51 AM" src="https://user-images.githubusercontent.com/24186167/70890555-a423c180-1fe5-11ea-989d-767dbf10d9fd.png">

The server will start and show you something like this:

<img width="1166" alt="Screenshot 2019-12-16 at 9 19 15 AM" src="https://user-images.githubusercontent.com/24186167/70890597-bdc50900-1fe5-11ea-82e7-df403d737c51.png">

Let me know if you're still having issues.

**Comment by colinricardo** [comment]
I don't have a connection string -- I should be able to clone the repo and run the app

**Comment by thislekan** [comment]
Hello @colinricardo 

I just cloned the app on a friend's laptop and it works fine (See the screenshot below for evidence). Please follow these steps to get the app working:

- from any directory on your PC run `git clone https://github.com/thislekan/codecubed-todo.git`
- run `cd codecubed-todo/app` && `yarn install`
- run `export GOOGLE_APPLICATION_CREDENTIALS="[PATH TO YOUR DOWNLOADED CREDENTIALS]"`
- run `yarn dev`

**Everything works fine at this point because I am not using a local version of mongoDB. I pushed the connection string to my mlab DB to avoid issues like this. Check the enviroments file in the app folder to confirm this**

![Image 17-12-2019 at 12 02 PM](https://user-images.githubusercontent.com/24186167/70993727-e4aa3a80-20cc-11ea-86ec-3015d121feaa.jpg)
